[package]
name = "eommong-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.11"
rocket_contrib= "0.4.11"
serde = { version = "1.0.152", features = ["derive"] }
diesel = "2.0.2"

